### ISSUE TITLE
Possible typos in readme

### ISSUE THREAD

**Issue by steveatgh** [beehive-lab/levelzero-jni#1]
Not sure, but there may be a couple of typos in the readme.

- in the "To compile to SPIR-V" section, the command line refers to a kernel file 'opencl-copy.cl' but the sample kernel in the repository is called 'copy_data.cl'

- the command line in the "To run" section looks like it has omitted the package path to the TestLevelZero class

**Comment by jjfumero** [comment]
I will close this issue. Feel free to open new issues for more questions/bugs/comments.
